#!/usr/bin/env bash

set -uo pipefail;

echo 'Usage: kctlenv <command> [<options>]

Commands:
   install       Install a specific version of Kubectl
   use           Switch a version to use
   uninstall     Uninstall a specific version of Kubectl
   list          List all installed versions
   list-remote   List all installable versions
   version-name  Print current version
   init          Update environment to use 'kctlenv' correctly.
   pin           Write the current active version to ./.kubectl-version
';

exit 0;
