#!/usr/bin/env bash
#
# Summary: Run an executable with the selected Kubectl version
#
# Usage: kctlenv exec <command> [arg1 arg2...]
#
# Runs an executable by first preparing PATH so that the selected Kubectl
# version's `bin' directory is at the front.
#
# For example, if the currently selected Kubectl version is 0.7.0:
#   kctlenv exec plan
#
# is equivalent to:
#   PATH="$KCTLENV_ROOT/versions/0.7.0/bin:$PATH" kubectl plan

set -uo pipefail;

####################################
# Ensure we can execute standalone #
####################################

function early_death() {
  echo "[FATAL] ${0}: ${1}" >&2;
  exit 1;
};

if [ -z "${KCTLENV_ROOT:-""}" ]; then
  # http://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac
  readlink_f() {
    local target_file="${1}";
    local file_name;

    while [ "${target_file}" != "" ]; do
      cd "$(dirname ${target_file})" || early_death "Failed to 'cd \$(dirname ${target_file})' while trying to determine KCTLENV_ROOT";
      file_name="$(basename "${target_file}")" || early_death "Failed to 'basename \"${target_file}\"' while trying to determine KCTLENV_ROOT";
      target_file="$(readlink "${file_name}")";
    done;

    echo "$(pwd -P)/${file_name}";
  };

  KCTLENV_ROOT="$(cd "$(dirname "$(readlink_f "${0}")")/.." && pwd)";
  [ -n "${KCTLENV_ROOT}" ] || early_death "Failed to 'cd \"\$(dirname \"\$(readlink_f \"${0}\")\")/..\" && pwd' while trying to determine KCTLENV_ROOT";
else
  KCTLENV_ROOT="${KCTLENV_ROOT%/}";
fi;
export KCTLENV_ROOT;

if [ -n "${KCTLENV_HELPERS:-""}" ]; then
  log 'debug' 'KCTLENV_HELPERS is set, not sourcing helpers again';
else
  [ "${KCTLENV_DEBUG:-0}" -gt 0 ] && echo "[DEBUG] Sourcing helpers from ${KCTLENV_ROOT}/lib/helpers.sh";
  if source "${KCTLENV_ROOT}/lib/helpers.sh"; then
    log 'debug' 'Helpers sourced successfully';
  else
    early_death "Failed to source helpers from ${KCTLENV_ROOT}/lib/helpers.sh";
  fi;
fi;

# Ensure libexec and bin are in $PATH
for dir in libexec bin; do
  case ":${PATH}:" in
    *:${KCTLENV_ROOT}/${dir}:*) log 'debug' "\$PATH already contains '${KCTLENV_ROOT}/${dir}', not adding it again";;
    *)
      log 'debug' "\$PATH does not contain '${KCTLENV_ROOT}/${dir}', prepending and exporting it now";
      export PATH="${KCTLENV_ROOT}/${dir}:${PATH}";
      ;;
  esac;
done;

#####################
# Begin Script Body #
#####################

kctlenv-exec "$@";
